#!/usr/bin/env bash
# Installs stub scripts for onboard.py into a directory of your choice.
# Stubs delegate to the repo file so updates are live without reinstalling.
#
# Usage:
#   bash scripts/install-onboard.sh [OPTIONS]
#
# Options:
#   --install-dir DIR       Where to write the stub scripts (required)
#   --onboarding-dir DIR    Default onboarding directory embedded in stubs (required)
#   --api-url URL           Default API URL embedded in stubs (default: http://localhost:8000)
#   --stub-name NAME        Base name for the stubs (default: awb-onboard)
#   --help                  Show this help
#
# Two stubs are installed:
#   <stub-name>           Normal pass: processes ready files
#   <stub-name>-archive   Archive pass: moves processed files to archive/
#
# Example (server/container install):
#   bash scripts/install-onboard.sh \
#     --install-dir /usr/local/bin \
#     --onboarding-dir /mnt/smb/onboarding \
#     --api-url http://awb-api:8000
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ONBOARD_PY="$SCRIPT_DIR/onboard.py"

INSTALL_DIR=""
ONBOARDING_DIR=""
API_URL="http://localhost:8000"
STUB_NAME="awb-onboard"

usage() {
    sed -n '/^# Usage:/,/^[^#]/{ /^[^#]/d; s/^# \{0,1\}//; p }' "$0"
    exit 0
}

die() { echo "error: $*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        --install-dir)    INSTALL_DIR="$2";    shift 2 ;;
        --onboarding-dir) ONBOARDING_DIR="$2"; shift 2 ;;
        --api-url)        API_URL="$2";        shift 2 ;;
        --stub-name)      STUB_NAME="$2";      shift 2 ;;
        --help|-h)        usage ;;
        *) die "unknown option: $1" ;;
    esac
done

[ -f "$ONBOARD_PY" ]    || die "onboard.py not found at $ONBOARD_PY"
[ -n "$INSTALL_DIR" ]   || die "--install-dir is required"
[ -n "$ONBOARDING_DIR" ] || die "--onboarding-dir is required"

mkdir -p "$INSTALL_DIR"

write_stub() {
    local dest="$1"
    local extra_args="${2:-}"
    cat > "$dest" << STUB_EOF
#!/usr/bin/env bash
# Generated by install-onboard.sh — delegates to the agent-workbench repo.
# Repo:          $SCRIPT_DIR
# onboard.py:    $ONBOARD_PY
exec uv run "$ONBOARD_PY" \\
  --onboarding-dir "$ONBOARDING_DIR" \\
  --api-url "$API_URL" \\
  ${extra_args:+$extra_args \\
  }"\$@"
STUB_EOF
    chmod +x "$dest"
}

MAIN_STUB="$INSTALL_DIR/$STUB_NAME"
ARCHIVE_STUB="$INSTALL_DIR/$STUB_NAME-archive"

write_stub "$MAIN_STUB"
write_stub "$ARCHIVE_STUB" "--archive"

echo "Installed stubs:"
echo "  $MAIN_STUB"
echo "  $ARCHIVE_STUB"
echo ""
echo "Baked-in defaults:"
echo "  onboarding-dir : $ONBOARDING_DIR"
echo "  api-url        : $API_URL"
echo "  onboard.py     : $ONBOARD_PY"
echo ""
echo "Usage:"
echo "  $STUB_NAME                  # process ready files"
echo "  $STUB_NAME --dry-run        # preview without changes"
echo "  $STUB_NAME-archive          # move processed files to archive/"
echo "  $STUB_NAME-archive --dry-run"
echo ""
echo "Suggested crontab entries:"
echo "  # Run onboarding pass every 15 minutes"
echo "  */15 * * * * $MAIN_STUB"
echo "  # Archive processed files nightly at 02:00"
echo "  0 2 * * * $ARCHIVE_STUB"

# Warn if the install dir is not on PATH
case ":$PATH:" in
    *":$INSTALL_DIR:"*) ;;
    *)
        echo ""
        echo "Note: $INSTALL_DIR is not in PATH. Add to your shell profile or /etc/environment:"
        echo "  export PATH=\"$INSTALL_DIR:\$PATH\""
        ;;
esac
